apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../common/skaffold.chicmoz-base-image.yaml
build:
  artifacts:
    - image: registry.digitalocean.com/aztlan-containers/explorer-ui-mainnet
      context: ../../../services/explorer-ui
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: "production"
          VITE_L2_NETWORK_ID: "MAINNET"
          VITE_CHICMOZ_ALL_UI_URLS: "Mainnet|https://beta.aztecscan.xyz,Testnet|https://testnet.beta.aztecscan.xyz,Devnet|https://devnet.beta.aztecscan.xyz"
          VITE_API_URL: "https://api.beta.aztecscan.xyz/v1"
          VITE_API_KEY: "temporary-api-key"
          VITE_WS_URL: "wss://ws.beta.aztecscan.xyz"
          VITE_DISCORD_URL: "https://discord.gg/xnw7fVXB7m"
          VITE_GITHUB_URL: "https://github.com/aztec-scan/chicmoz"
          VITE_VERSION_STRING: "{{.VERSION_STRING}}"
      requires:
        - image: registry.digitalocean.com/aztlan-containers/chicmoz-base
          alias: BASE
manifests:
  rawYaml:
    - ./mainnet/service.yaml
    - ./mainnet/httproute.yaml
    - ./mainnet/deployment.yaml
deploy:
  kubectl:
    flags:
      apply: ["--force"]
