apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: websocket-event-publisher-mainnet
  namespace: chicmoz-prod
  labels:
    app.kubernetes.io/name: websocket-event-publisher
    app.kubernetes.io/part-of: chicmoz-prod
spec:
  parentRefs:
    - name: aztecscan-gateway
      sectionName: ws-http
    - name: aztecscan-gateway
      sectionName: ws-https
    - name: aztecscan-gateway
      sectionName: ws-mainnet-http
    - name: aztecscan-gateway
      sectionName: ws-mainnet-https
  hostnames:
    - ws.beta.aztecscan.xyz
    - ws.mainnet.beta.aztecscan.xyz
  rules:
    - backendRefs:
        - name: websocket-event-publisher-mainnet-service
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
