apiVersion: v1
kind: Service
metadata:
  name: websocket-event-publisher-mainnet-service
  namespace: chicmoz-prod
spec:
  selector:
    app: websocket-event-publisher-mainnet-label
  ports:
    - name: websocket
      protocol: TCP
      port: 80
      targetPort: websocket-port
