apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: cache-system
type: Opaque
stringData:
  redis-password: "clPrsWNEOPCkLrMQwfkgHGUY1lVNjnt4Uta8yAuZM"
  redis-host: "redis.cache-system.svc.cluster.local"
  redis-port: "6379"
