apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: explorer-ui-testnet
  namespace: chicmoz-prod
  labels:
    app.kubernetes.io/name: explorer-ui
    app.kubernetes.io/part-of: chicmoz-prod
spec:
  parentRefs:
    - name: aztecscan-gateway
      sectionName: ui-testnet-http
    - name: aztecscan-gateway
      sectionName: ui-testnet-https
  hostnames:
    - testnet.beta.aztecscan.xyz
  rules:
    - backendRefs:
        - name: explorer-ui-testnet-service
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
