apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: websocket-event-publisher-sandbox
  namespace: chicmoz
  labels:
    app.kubernetes.io/name: websocket-event-publisher
    app.kubernetes.io/part-of: chicmoz-local
spec:
  parentRefs:
    - name: chicmoz-gateway
      sectionName: ws-sandbox
  hostnames:
    - ws.sandbox.chicmoz.localhost
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: websocket-event-publisher-sandbox-service
          port: 80
