apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: explorer-api-mainnet-security
  namespace: chicmoz-prod
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: explorer-api-mainnet
  cors:
    allowOrigins:
      - https://docs.beta.aztecscan.xyz
      - https://beta.aztecscan.xyz
      - https://mainnet.beta.aztecscan.xyz
    allowMethods:
      - GET
      - PUT
      - POST
      - DELETE
      - PATCH
      - OPTIONS
    allowHeaders:
      - DNT
      - Keep-Alive
      - User-Agent
      - X-Requested-With
      - If-Modified-Since
      - Cache-Control
      - Content-Type
      - Range
      - Authorization
      - access-control-allow-credentials
      - x-api-key
    allowCredentials: true
    exposeHeaders:
      - x-api-key
    maxAge: 24h
  extAuth:
    timeout: 5s
    http:
      backendRefs:
        - name: auth-service
          namespace: chicmoz-prod
          port: 80
      path: /_external-auth-envoy
      headersToBackend:
        - x-forwarded-for
        - x-forwarded-proto
        - x-forwarded-host
        - x-forwarded-uri
        - x-envoy-original-path
        - x-request-id
        - ":authority"
        - ":scheme"
        - ":path"
    failOpen: false
