apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kafka-ui
  namespace: chicmoz
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/part-of: chicmoz-local
spec:
  parentRefs:
    - name: chicmoz-shared-gateway
      sectionName: kafka
  hostnames:
    - kafka.localhost
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kafka-ui
          port: 80
