apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: explorer-ui-mainnet
  namespace: chicmoz-prod
  labels:
    app.kubernetes.io/name: explorer-ui
    app.kubernetes.io/part-of: chicmoz-prod
spec:
  parentRefs:
    - name: aztecscan-gateway
      sectionName: ui-http
    - name: aztecscan-gateway
      sectionName: ui-https
    - name: aztecscan-gateway
      sectionName: ui-mainnet-http
    - name: aztecscan-gateway
      sectionName: ui-mainnet-https
  hostnames:
    - beta.aztecscan.xyz
    - mainnet.beta.aztecscan.xyz
  rules:
    - backendRefs:
        - name: explorer-ui-mainnet-service
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
