apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: websocket-event-publisher-testnet
  namespace: chicmoz-prod
  labels:
    app.kubernetes.io/name: websocket-event-publisher
    app.kubernetes.io/part-of: chicmoz-prod
spec:
  parentRefs:
    - name: aztecscan-gateway
      sectionName: ws-testnet-http
    - name: aztecscan-gateway
      sectionName: ws-testnet-https
  hostnames:
    - ws.testnet.beta.aztecscan.xyz
  rules:
    - backendRefs:
        - name: websocket-event-publisher-testnet-service
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
