apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: explorer-api-sandbox-rewrite
  namespace: chicmoz
spec:
  urlRewrite:
    path:
      type: ReplaceRegexMatch
      replaceRegexMatch:
        pattern: ^/v1/[^/]+/(.*)$
        substitution: '/\1'
