apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: aztecscan-client-traffic-policy
  namespace: chicmoz-prod
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: aztecscan-gateway
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
