apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: swagger
  namespace: chicmoz-prod
  labels:
    app.kubernetes.io/name: swagger
    app.kubernetes.io/part-of: chicmoz-prod
spec:
  parentRefs:
    - name: aztecscan-gateway
      sectionName: swagger-http
    - name: aztecscan-gateway
      sectionName: swagger-https
  hostnames:
    - docs.beta.aztecscan.xyz
  rules:
    - backendRefs:
        - name: swagger-service
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
