apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway
  labels:
    app.kubernetes.io/name: chicmoz-local
    app.kubernetes.io/part-of: gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  description: Envoy GatewayClass for local testing
