apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: chicmoz-gateway
  namespace: chicmoz
  labels:
    app.kubernetes.io/name: chicmoz-gateway
    app.kubernetes.io/part-of: chicmoz-local
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: api-sandbox
      hostname: api.sandbox.chicmoz.localhost
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: ui-sandbox
      hostname: sandbox.chicmoz.localhost
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: ws-sandbox
      hostname: ws.sandbox.chicmoz.localhost
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: aztec-sandbox
      hostname: aztec.sandbox.chicmoz.localhost
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: eth-sandbox
      hostname: eth.sandbox.chicmoz.localhost
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: swagger
      hostname: swagger.chicmoz.localhost
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: dashboard
      hostname: dashboard.chicmoz.localhost
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: kafka
      hostname: kafka.localhost
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
