apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: explorer-ui-sandbox
  namespace: chicmoz
  labels:
    app.kubernetes.io/name: explorer-ui
    app.kubernetes.io/part-of: chicmoz-local
spec:
  parentRefs:
    - name: chicmoz-sandbox-gateway
      sectionName: ui-sandbox
  hostnames:
    - sandbox.chicmoz.localhost
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: explorer-ui-sandbox-service
          port: 80
