apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: anvil-ethereum-node
  namespace: chicmoz
  labels:
    app.kubernetes.io/name: anvil-ethereum-node
    app.kubernetes.io/part-of: chicmoz-local
spec:
  parentRefs:
    - name: chicmoz-sandbox-gateway
      sectionName: eth-sandbox
  hostnames:
    - eth.sandbox.chicmoz.localhost
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: anvil-ethereum-node
          port: 80
